language: python

python:
  - "3.6"

addons:
  apt:
    packages:
      - libboost-all-dev

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-6 -y
  
install:

  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create --channel conda-forge --override-channels -q -n test-environment python=$TRAVIS_PYTHON_VERSION arrow-cpp=0.11.*
  - source activate test-environment
  - CC=gcc-6 CXX=g++-6 python setup.py build_ext --inplace
  - pip3 install -r requirements.txt

script:
  - python3 -m pytest pyqstrat
  