language: python

matrix:
    include:
        - os: linux
          python: 3.6
          env: TOXENV=py36

addons:
  apt:
    packages:
      - gdb
      - apport

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

install:
  - sudo apt-get install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create --channel conda-forge --override-channels -q -n test-environment python=$TRAVIS_PYTHON_VERSION arrow-cpp pybind11 pytest pandas numpy matplotlib scipy ipython pyarrow
  - source activate test-environment
  - CXX=g++-5 CC=g++-5 python setup.py build_ext --inplace

script:
  - ulimit -c unlimited -S
  - which python
  - python -m pytest pyqstrat || RESULT=$?
  - ls -l
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $HOME/miniconda/bin/python core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
   