language: cpp

compiler:
  - gcc

matrix:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    
before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev
  
python:
  - "3.6"
    
install: 
  - "pip3 install -r requirements.txt"
  - "python setup.py build_ext"
    
script: 
    - "python3 -m pytest pyqstrat"