cache:
- C:\Tools\vcpkg\installed

configuration: Release

notifications:
  - provider: Email
    to:
      - abbasi.sal@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
    
environment:
  VCPKG_DIR: C:\Tools\vcpkg
  PYTHON: "C:\\conda"
  CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
  PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                      # of 32 bit and 64 bit builds are needed, move this
                      # to the matrix section.
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      PLATFORM: x64
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
      ARCHITECTURE: x86_amd64

init:
 - cd %VCPKG_DIR%
 - echo.set(VCPKG_BUILD_TYPE release)>> %VCPKG_DIR%\triplets\%PLATFORM%-windows.cmake
 - vcpkg version
 - cd %APPVEYOR_BUILD_FOLDER%

install:
  - vcpkg install 
      boost-iostreams
      --triplet %PLATFORM%-windows

  - vcpkg list
  - set PATH=%VCPKG_DIR%\installed\%PLATFORM%-windows\bin;%PATH%
  - if "%PYTHON_VERSION%" == "3.6" set "BASE_PYTHON_VERSION=3"
  - if "%PYTHON_ARCH%" == "64" set "ARCH_LABEL=-x64"
  - conda info -a
  - conda config --set always_yes yes
  - conda create --channel conda-forge --override-channels -q -n test-environment python=%PYTHON_VERSION% arrow-cpp pybind11 pandas numpy matplotlib pyarrow pytest

build_script:
  - call "%VCVARSALL%" %ARCHITECTURE%
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%CONDA_ROOT%\\Scripts\\activate test-environment"
  - echo CONDA_PREFIX %CONDA_PREFIX%
  - echo PATH %PATH%
  - pip install scipy
  - conda list
  - conda info -a
  - python -c "import sys; print(sys.version)"
  - python -c "import sys; print(sys.executable)"
  - python -c "import sys; print(sys.prefix)"
  - python --version
  - python setup.py build_ext --inplace
  - python -m pytest pyqstrat

  
